### ISSUE TITLE
Could we put neopixels in the snakes eyes?

### ISSUE THREAD

**Issue by sarahfenway** [kirknorthrop/circuitpython-badge#12]

**Comment by deshipu** [comment]
We can add any number of lights, sensors, speakers, etc. to the board, however, every such part will add to the cost and will use up GPIO pins. The initial design was an attempt to strike a balance, but without any real specifications that was difficult to do. I assumed that since we already have 154 LEDs on there, two additional ones wouldn't add much.

We should probably sit down and decide what the board should contain, based on testing the prototypes we have right now, and then base the redesign on that.

**Comment by AidanTek** [comment]
I'm not sure how serious this idea was (sorry if it was serious!!) a midway compromise could be some SMD leds just linked to power rail (power on and battery indicators could be cool!) 

Just to point out though that the pysnakes eyes are already there and being used for cord connection - I suppose it could be a nose piercing though? ;)

**Comment by deshipu** [comment]
CircuitPython has a support for a small APA102 LED for status indicator, I think it would make sense to have at least one of those (and since they can be chained, it doesn't cost extra GPIO to have more). Maybe not necessarily in the eyes, but somewhere.
