### ISSUE TITLE
User friendly inputs

### ISSUE THREAD

**Issue by sarahfenway** [kirknorthrop/circuitpython-badge#13]
Can we bring some inputs and outputs to the bottom of the board? Like how the microbit does it with a huge hole/connector. Obviously hard because of the perforation, but would it matter hugely if we had to lose them when removing the name?

**Comment by deshipu** [comment]
Yes, user inputs are a big problem, and I've spent some time considering different options.

I didn't want to require a special connector, like the Micro:bit does, because my experiences with it are less than stellar, and I don't want people to have to buy additional special hardware to be able to play with it.

Crocodile clips and banana plugs are equally difficult to get, and provide very bad connection, especially when the whole thing is being worn on your neck.

I was considering simple male pin headers, like many development boards use, but the problem is that people usually don't go to conferences with a soldering iron with them, and teaching people to solder at the conference itself, while fun, could end up in a disaster. Male pin headers are also problematic, because it's easy to short them and/or bend them in transport, when people will be travelling with them in the baggage.

Female pin headers are an interesting option, because you can use jumper wires with them to build things without really having to solder, and they are much safer both electrically and mechanically.

Finally, I decided to use the grove connectors, because they are compact, keyed (so it's impossible to connect anything in reverse), snap into place and provide very good connections. For experimenting, we would need to provide a selection of sensors and other extensions anyways, so it's not a big problem to add the grove cables to them to make them easy to connect.

I am open to other ideas with this.

**Comment by sarahfenway** [comment]
I think the thought with the microbit holes is that they allow a user to stick a bit of wire through and twist it together to make a connection. Yes, I am aware of how horrible this is but it is a conceivable use case when at a conference you don't have (or want to have) soldering irons or dupont connectors, which are hardly robust or good at staying in the holes you put them in.

**Comment by deshipu** [comment]
In that case wouldn't screw terminals be better?

**Comment by AidanTek** [comment]
I think male/female headers are fine - you can get male/female jumper wires for basic breadboarding, and if anyone wants to go really crazy they can make something to socket on to it - but I don't think you need to be responsible for that! I guess my thoughts on this were more that people might want to do small workshops based on using the badge that allow for some extra connections as opposed to people soldering up a wearable... 

I'm also not against having those big chunky sockets for bananas/crocs - they aren't practical by any means but they are great for plug and play. Some MCUs have capacitive sensing on their GPIO pins as well (which is usually a headache, but also kinda fun!)

**Comment by deshipu** [comment]
I have some very good results with male headers inserted (without soldering) into staggered holes in the PCB, and then plugged into a breadboard. I tried this with my game console, and so far it works good:
![img_20180905_114141](https://user-images.githubusercontent.com/1181357/46263017-e577a080-c509-11e8-9fb8-cdd38269cb07.jpg)
Note how it's exactly the same height as the battery holder. Also, you can even walk around with the mini-breadboard (and possibly some stuff in it) in place.

**Comment by AidanTek** [comment]
Looks great to me!

**Comment by Isioviel** [comment]
I love it! Male pins on the back (protected slightly because of the height of the battery), that can pop straight into a breadboard? And/or female connectors on the front for immediate use?
I've also seen (on a Kitronik product maybe?) slightly wobby through holes, so that straight pin headers fit in then get stuck slightly, so they hang in without soldering, sorry that's an awful description.
I like pin headers better than specific connectors, because it's easy then to just plug whatever you want in without having to solder on the right leads. The croc clip holes on the microbit are nice for testing / kids' workshops, but annoying if you want to walk around with things plugged in. Jump leads are also cheap enough that we could possibly provide a few with the badge (or maybe an electronics supplier e.g. Kitronik or Pimoroni would be interested in running a stall to sell components... is that allowed?).
Either way, workshops would be easy to plan & run if we could use breadboards & standard components.
