### ISSUE TITLE
SMD LEDs with white silkscreen behind it like the microbit

### ISSUE THREAD

**Issue by sarahfenway** [kirknorthrop/circuitpython-badge#14]

**Comment by deshipu** [comment]
We could do that, however there are a few issues with it:

- it would be more expensive to fabricate the board with so much SMD soldering,
- it would be difficult to fit the chip that controls the LEDs on the remaining board space (right now it's under the LED matrices),
- the LED's wouldn't be diffused like they are now, so the image wouldn't look as nice.

**Comment by deshipu** [comment]
Another option is to use a TFT or OLED screen. There are some very cheap TFT screens, but they are not very power-efficient — the current display lasts for 2-3 days on the 3 alkaline batteries, a TFT screen probably wouldn't last as long. OLED screens are more efficient and brighter, but the cheap ones are all very small, unsuitable for displaying anything we would want to have visible from a large distance.

**Comment by AidanTek** [comment]
I think the LED matrix is ok, it is simple and easy to program. An OLED isn't too much different I guess but I think being able to run for days on AAA batteries is the way forwards. I would love it to be something more like this though... [Full Colour Matrix](https://www.amazon.co.uk/Generic-Display-60x60mm-Arduino-Colorduino-Blue-Green-Red/dp/B00E5B7PE4/ref=sr_1_4_acs_a9_resurface_1_B00E5B7PE4_4?ie=UTF8&qid=1538326614&sr=8-4-acs&keywords=matrix+led) You know it's the right thing to do ;) 

I think I need to order some of those!!

**Comment by deshipu** [comment]
Well, I have a couple of similar ones. The problem is that it's 192 LEDs to control, in what is a de facto 8x24 matrix. That is a lot of LEDs: you would need 32 GPIO pins if you did it directly in software, or you would need to use a chip similar to the IS31FL3733 I used in the current prototype, but bigger (that one only allows up to 16x12), for example the IS31FL3741 (up to 39x9).

Another option is to keep the current chip, and use a bi-color matrix. I did that with one of my projects (https://hackaday.io/project/21578-pewpew-featherwing). With just on-off control (with a cheap HT16K33 chip) you get green, red and yellow colors. With the ISS chip we use now, you would get all the shades between them as well.

The problem with both of those is lower resolution, though — barely enough to display one letter at a time.
