### ISSUE TITLE
What do you want to connect to the badge?

### ISSUE THREAD

**Issue by deshipu** [kirknorthrop/circuitpython-badge#16]
I think it would let us figure out the number and kind of connectors to put on the badge if we had a better idea about what would people connect to them. To start the discussion, I will list some ideas that I had. Let's remember that we are talking about a conference setting, where people usually don't bring pockets full of electronic components and where most parts would probably need to be provided by the organizers.

- A speaker. This is a nice thing to have, especially since the microcontroller on the badge has a real DAC output, and is capable of generating pretty nice audio, including playing ringtone melodies. I didn't put a speaker on the badge by default, because I don't it to be a nuisance during the presentations.
- Neopixels. It's always nice to have some additional strings of neopixels attached somewhere on you, and controlled with the badge. The problem here is power: neopixels have been designed for room lighting applications, not for signalling, and they use up a lot of battery power. They also prefer to have a 5V signal, while our device is 3.3V.
- Hobby servos. You can easily control servos with CircuitPython, and it's always exciting to see something move in response to your program. The same power as with neopixels applies.
- Photoresistor. It's nice to have the badge react to light. We could even have one built-in, if we wanted.
- Temperature/humidity/atmospheric pressure sensor. Not sure who would like to turn themselves into a weather station, but people seem to enjoy this somehow.
- Microphone. We won't be able to record audio, unless we somehow exactly replicate the setup from the Circuit Playground Express, but we should be able to react to sound or to make equalizers and other sound visualizations.

Any more ideas?

**Comment by AidanTek** [comment]
I think that is a pretty sensible list, I use programmable LEDs a lot for introductory classes - they are fun and invite people to experiment. They do work ok at 3.3V, just at a lower brightness (The Adafruit Circuit Playground is an example). 30mA per led is a pretty safe figure to bet on.

I think 4 to 6 GPIO is probably more than sufficient - it just allows for a little bit of plug and play, all of those parts you mentioned could be demonstated in introductory workshops

Some other favourites at the moment are DC computer fans and miniature DC vibration motors (yeah don't ask!!). They both run on very low current - the phone vibrators are made for 3.3V and use under 10mA

**Comment by deshipu** [comment]
The microcontroller I used — SAMD21 — is a bit more delicate than the old AVR chips that could source even 20mA per pin, and can only source around 6-8mA (it can sink a few mA more, but not by much). Motors would require a mosfet or a H-bridge driver — not just because of the current draw, but also because of the backlash current that they generate when they are stopped.

**Comment by AidanTek** [comment]
Yes very true and fair enough!

**Comment by deshipu** [comment]
One more thing that can be connected:

- Any physical object for touch input.

**Comment by AidanTek** [comment]
Great! So capacitive sensing?

**Comment by deshipu** [comment]
Yes, CircuitPython supports that on the SAMD chips: https://circuitpython.readthedocs.io/en/latest/shared-bindings/touchio/__init__.html

**Comment by Isioviel** [comment]
Re motors: would an L9110s motor driver be sufficient? It's what I use with micro:bit & arduino with no issues. They use 4 GPIO pins (ideally with analogue/PWM) they're super cheap & I have loads of them (thinking for a quick & cheap robotics workshop specifically). We don't even need to use all four pins actually if we're just doing a race, could get away with just one motor.

I love the idea of a built in photoresistor, it's such a nice visual to get the screen reacting  to changes in light for example. The microbit uses the LED display as a light sensor, is that something that would be possible with the badge's display too?
https://support.microbit.org/support/solutions/articles/19000024023-how-does-the-light-sensing-feature-on-the-micro-bit-work-
(This works with micropython on mu now despite what the link says)

Things I'd personally, and from working in education, like to connect are: Neopixels, servos and motors, but I understand (and have experienced the frustration of!) the power issues. Could an additional power line be built in (with space for a second set of batteries) so that Neopixels, servos & other outputs could be powered separately and just get the signal from / share ground with the microcontroller? Or is that inviting trouble (and adding additional cost & complexity).

Speakers are also a big hit in education, especially if there are premade tunes people can play for the non-musical of us! I agree it's not ideal for a conference setting, but it's a great extra. That combined with capacitive touch to make fruit pianos...

You've built a lot of great features into the badge already, so I think even with limited GPIO capability they'd keep people busy and happy for a good while!

**Comment by deshipu** [comment]
I think it would make a lot of sense to have "high power" outputs, where you could connect motors or other more demanding things, as long as they would be clearly marked and so not easy to confuse with the others. As long as we can fit it on the board and in the budget, of course, but that will be a separate discussion at some point, right now I just want to collect ideas.
We will probably be making at least one more prototype, depending on what changes we need. It would be great to switch to SAMD51, now that it is fully supported, and that gives us more GPIO pins as well.

**Comment by AidanTek** [comment]
For more power the USB supply line could be broken out to GPIO pins, then if you need to connect a +5V wall adaptor or more chunky batteries, you can do it that way. Use an LDO regulator with 3v3 output and with wide input voltage range - the Teensy 3.6 has a pretty good one, the LP38691. Only 500mA but you can consider powering motors from your 5V rail and controlling them with 3v3 logic and the likes. With my students I tend to use ULN2003a and SN754410 to drive motors and steppers - those are both pretty ancient chips but they just do what they say on the tin!
