### ISSUE TITLE
CircuitPython 3.0

### ISSUE THREAD

**Issue by sarahfenway** [kirknorthrop/circuitpython-badge#9]
CircuitPython was only running the 3.0 beta - can we upgrade to the full release?

**Comment by deshipu** [comment]
Yes, of course. It was running beta because that's what was available at the time. A version 4.0 will be released soon (and I suspect that by the time of the conference, also 5.0). Fortunately, building a new version is just a question of copying the board definition files and the badge.py library to be frozen.

**Comment by sarahfenway** [comment]
I don't remember who asked this (I think @AidanTek), and he seemed to think we needed another file to compile it? (Sorry if this is incorrect - I have no idea at all about compiling CircuitPython)

**Comment by deshipu** [comment]
You need the board definition, which is now added to this repository at https://github.com/circuitpython-badge/circuitpython-badge/tree/master/hardware/board — you just need to copy that to a subdirectory in `ports/atmel-samd/boards` and then from `ports/atmel-samd` run `make BOARD=name-of-that-subdirectory`. I will add a compiled firmware for CircuitPython 3.0.2 to the releases page.

**Comment by deshipu** [comment]
I added the compiled firmware with flashing instructions at https://github.com/circuitpython-badge/circuitpython-badge/releases/tag/cp3.0.2

**Comment by AidanTek** [comment]
It wasn't me - I haven't done it before. I will have a crack at upgrading firmware sometime in the week
